---
title: "LAB 1."
author: "Hoyoung Park"
date: "October 2, 2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
fontsize: 10pt
geometry: margin=1in
header-includes:
- \usepackage{graphicx}
- \usepackage{kotex}
- \usepackage{natbib}
- \usepackage{amsmath,amsthm,amssymb,epsfig}
- \usepackage{hyperref}
- \setlength{\oddsidemargin}{0 in}
- \setlength{\evensidemargin}{0 in}
- \setlength{\topmargin}{-0.6 in}
- \setlength{\textwidth}{6.5 in}
- \setlength{\textheight}{8.5 in}
- \setlength{\headsep}{0.75 in}
- \setlength{\parindent}{0 in}
- \setlength{\parskip}{0.1 in}
- \let\hat\widehat
- \newcommand{\by}{\mathbf{y}}
- \newcommand{\bH}{\mathbf{H}}
highlight: tango
number_sections: yes
fig_caption: yes
pdf_document: Lab.1
documentclass: article
---

# data loading
```{r}
rm(list = ls())
data.exampe<-readRDS("./data.exampe.rds")
str(data.exampe)
```



```{r}
#-----------------------------------------------------------------------------------------#
#-----------------------------------------------------------------------------------------#
#------------------------------ SRS for wage estimation ----------------------------------#
#-----------------------------------------------------------------------------------------#
#-----------------------------------------------------------------------------------------#
# set.seed(1015)
wage.vector<-c();
for( i in 1 : length(data.exampe)){
  wage.vector<-c(wage.vector, data.exampe[[i]][,3]) # get wages from each location
}
N<-length(wage.vector) # population number
true.mean.wage<-mean(wage.vector) # true wage mean
true.var.wage<-var(wage.vector)*(N-1)/N # true wage var

# Check CLT 
par(mfrow=c(2,2)) # make subplots
sample.number<-c(5,10,50,500)
for (i in 1:4){
  wage.sample.mean<-c()
  for (j in 1:1000){
    wage.sample<-sample(wage.vector,sample.number[i],replace=F) # sample (5, 10, 50, 500) data points from wage
    wage.sample.mean[j]<-mean(wage.sample) # get sample mean
  }
  normalize.srs.mean.wage<-(wage.sample.mean-true.mean.wage)/sqrt(true.var.wage/sample.number[i]) # normalize
  
  
  hist(
    normalize.srs.mean.wage,
    xlim=c(-5,5),
    ylim=c(0,0.6),
    probability=T, # or show frequency
    main=paste("SRS sample mean dist with n=", sample.number[i])
  )
  
  y<-seq(-5, 5, 0.01)
  fy<-dnorm(y, 0, 1)
  lines(y, fy,col="red")
  
  legend(
    "topright",
    "Standard normal density function", 
    lwd=c(1),
    lty=c(1),
    col=c("red"),
    cex=0.5
  )
}
```



```{r}
#-----------------------------------------------------------------------------------------#
#-----------------------------------------------------------------------------------------#
#----------------------------- Sample allocation    --------------------------------------#
#-----------------------------------------------------------------------------------------#
#-----------------------------------------------------------------------------------------#


N_h<-c()
true.mean.wage_h<-c() # true mean wage per area
true.var.wage_h<-c() # true var wage per area
for(i in 1:length(data.exampe)){
  N_h<-c(N_h,dim(data.exampe[[i]])[1])  # 각 층의 모집단 수
  true.mean.wage_h<-c(true.mean.wage_h,mean(data.exampe[[i]][,3])) # 각 층의 임금 평균 참값 
  true.var.wage_h<-c(
    true.var.wage_h,
    var(data.exampe[[i]][,3])*(dim(data.exampe[[i]])[1]-1)/dim(data.exampe[[i]])[1]
  ) # 각 층의 임금 분산 참값
}
N<-sum(N_h)
D=1 # 최대 오차 허용한계 = +-2 -> D=2^2/4=1

# Neyman allocation (c_h=c, c_h : 비용함수 )
# Neyman allocation total sample number
n_neyman<-round((sum(N_h*sqrt(true.var.wage_h))^2)/(N^2*D+sum(N_h*true.var.wage_h))) 
# Neyman allocation sample number per area
n_neyman_h<-round((N_h*sqrt(true.var.wage_h))/(sum(N_h*sqrt(true.var.wage_h)))*n_neyman) 

# proportional allocation (n_h = c*N_h, c= constant)
# Proortion allocation total sample number
# Proortion allocation sample number per area
n_prop<-round((sum(N_h*true.var.wage_h))/(N*D+sum(N_h*true.var.wage_h)/N))
n_prop_h<-round((N_h/N)*n_prop)


# Comparision : Neyman and SRS
# We approximate MSE using 1000 iterations
wage.est.srs<-c()
wage.est.neyman<-c()
for(j in 1:1000){ # do it 1000 times
  wage.sample.neyman<-c()
  for(i in 1:10){ # loop through each location
    wage.sample.neyman<-c(
      wage.sample.neyman,
      mean(sample(data.exampe[[i]][,3], n_neyman_h[i], replace=F))
    ) 
  }
  wage.est.neyman[j]<-sum(wage.sample.neyman*N_h/N)
  
  wage.sample.srs<-sample(wage.vector,n_neyman,replace=F) 
  wage.est.srs[j]<-mean(wage.sample.srs)
}

cat(
  "Neyman allocation MSE is: ",
  mean((wage.est.neyman-true.mean.wage)^2)
)
cat(
  "SRS MSE is: ",
  mean((wage.est.srs-true.mean.wage)^2)
)
cat(
  "MSE ratio of the Neyman allocation to SRS is: ",
  mean((wage.est.neyman-true.mean.wage)^2)/mean((wage.est.srs-true.mean.wage)^2)
)

# Comparision : Proportional and SRS
# We approximate MSE using 1000 iterations
wage.est.srs<-c()
wage.est.prop<-c()
for(j in 1:1000){
  wage.sample.prop<-c()
  for(i in 1:10){
    wage.sample.prop<-c(
      wage.sample.prop,
      mean(sample(data.exampe[[i]][,3], n_prop_h[i], replace=F))
    ) 
  }
  wage.est.prop[j]<-sum(wage.sample.prop*N_h/N)
  
  wage.sample.srs<-sample(wage.vector,n_prop,replace=F)
  wage.est.srs[j]<-mean(wage.sample.srs)
}

cat(
  "Proportion allocation MSE is: ",
  mean((wage.est.prop-true.mean.wage)^2)
)
cat(
  "SRS MSE is: ",
  mean((wage.est.srs-true.mean.wage)^2)
)
cat(
  "MSE ratio of the Proportion allocation to SRS is: ",
  mean((wage.est.prop-true.mean.wage)^2)/mean((wage.est.srs-true.mean.wage)^2)
)
```

```{r}
#-----------------------------------------------------------------------------------------#
#-----------------------------------------------------------------------------------------#
#----------------------------- post-stratification    ------------------------------------#
#-----------------------------------------------------------------------------------------#
#-----------------------------------------------------------------------------------------#


Area<-c(
  rep("A1", dim(data.exampe[[1]])[1]),
  rep("A2", dim(data.exampe[[2]])[1]),
  rep("A3", dim(data.exampe[[3]])[1]),
  rep("A4", dim(data.exampe[[4]])[1]),
  rep("A5", dim(data.exampe[[5]])[1]),
  rep("A6", dim(data.exampe[[6]])[1]),
  rep("A7", dim(data.exampe[[7]])[1]),
  rep("A8", dim(data.exampe[[8]])[1]),
  rep("A9", dim(data.exampe[[9]])[1]),
  rep("A10", dim(data.exampe[[10]])[1])
)

# Comparision : Post-stratification and SRS
# We approximate MSE using 1000 iterations
n.post=(n_neyman + n_prop)/2 # we choose total sample number by (n_neyman+n_prop)/2
wage.est.srs<-c()
wage.est.post<-c()  
n.post_h<-c()
wage.est.post_h<-c()

for(j in 1:1000){
  # SRS
  sample_index<-sample(1:N, n.post, replace=F) # random vector
  wage.vector.sample<-wage.vector[sample_index] # sample wage data points
  wage.est.srs[j]<-mean(wage.vector.sample) # mean by simple random sample
  
  for(i in 1:length(data.exampe)){ # loop through each location
    n.post_h[i]<-sum(Area[sample_index]==paste("A", i, sep="")) 
    wage.est.post_h[i]<-mean(wage.vector.sample[Area[sample_index]==paste("A", i, sep="")])
  }
  
  wage.est.post[j]<-sum(N_h/N*wage.est.post_h)
}

cat(
  "post-stratification MSE is: ", 
  mean((wage.est.post-true.mean.wage)^2)
)
cat(
  "SRS MSE is: ", 
  mean((wage.est.srs-true.mean.wage)^2)
)
cat(
  "MSE ratio of the Proportion allocation to SRS is: ",
  mean((wage.est.post-true.mean.wage)^2)/mean((wage.est.srs-true.mean.wage)^2)
)
```
